/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturaFor;

public class App {
    
    public static void main(String[] args) {
        
        for(int i = 0; i <= 10; i++){
            
        }
    }
}

// Apenas demonstração da estrutura FOR