/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VariaveisTiposOperadores;

public class App {
    
    public static void main(String[] args) {
        
        // Tipo primitivos
        // As variáveis podem ou não ser inicializadas
        int idade;
        float cotacaoDolar = 5.0f;
        double cotacaoEuro = 6.0d;
        char genero = 'F'; // Armazena apenas uma letra
        byte ponto = 0; // Armazena variável numérica inteira
        boolean estaCadastrado = false; // Armazena valores lógicos (true or false)
        
        // Tipo não primitivo
        String nome = "Esse é um texto de uma variável String"; // Armazena um texto
        
        
        // Operadores
        /*  + -> Soma
            - -> Subtração
            / -> Divisão
            * -> Multiplicação
            % -> Resto da divisão
        */
    }
}
