/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturaEscolha;

public class App {

    public static void main(String[] args) {

        int codigoProduto = 2;

        switch (codigoProduto) {

            case 1:
                System.out.println("1");
                break;

            case 2:
                System.out.println("2");
                break;
                
            default:
                System.out.println("Default");
        }
    }
}
