/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExercicioQuatorze;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        
        int valor1;
        int valor2;
                
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("Digite um número: ");
        valor1 = scanner.nextInt();
        
        System.out.println("Digite outro número: ");
        valor2 = scanner.nextInt();
        
        if(valor1 > valor2){
            System.out.println("O valor " + valor1 + " é maior");
        }else {
            System.out.println("O valor " + valor2 + " é maior");
        }
                
    }
}
