/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Classes;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        
        Pessoa objetoPessoa = new Pessoa();
        
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("Digite o peso da pessoa: ");
        objetoPessoa.setPeso(scanner.nextFloat());
        
        System.out.println("Digite a altura da pessoa: ");
        objetoPessoa.setAltura(scanner.nextFloat());
        
        System.out.println("IMC = " + objetoPessoa.calcularIMC());
    }
}
